# Generated by Django 2.1.2 on 2019-02-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20190211_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_condition',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=10),
            preserve_default=False,
        ),
    ]
