# Generated by Django 2.1.2 on 2019-03-10 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20190310_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdibs',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='inventory.Item'),
        ),
    ]
