# Generated by Django 2.1.2 on 2019-03-10 03:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0006_auto_20190310_1055'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userdibs',
            unique_together={('item', 'user')},
        ),
    ]
