# Generated by Django 2.1.2 on 2019-03-10 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_item_user_dibs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='item_user_dibs',
        ),
    ]
